name: Upload code docs to TerminusCMS
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Clone JSDoc template
      run: git clone https://github.com/terminusdb-labs/jsdoc-terminusdb-template.git
    - name: Run NPM Install
      run: npm i
    - name: Run JSDoc
      run: npx jsdoc --template ./jsdoc-terminusdb-template --recurse ./lib/ > docs.json || true
    - name: Upload to TerminusCMS
      run: |
        curl -H 'Authorization: Token ${{ secrets.TERMINUSCMS_TOKEN}}' \
          -H 'Content-Type: application/json' \
          '${{ secrets.TERMINUSCMS_URL}}' -d @./docs.json
